version: "3"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5765:5432"
    volumes:
      - ./init.docker.sql:/docker-entrypoint-initdb.d/01_create_tables.sql